spring:
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/nvshen?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: root

mybatis:
   type-aliases-package: com.example.demo.mapper
   mapper-locations: mapper/*Mapper.xml
